/**
 * Marp CSS theme generator.
 *
 * Takes a normalized ExtractedPresentation and produces a valid Marp CSS
 * theme file in the themes/ directory. The generated theme mirrors the
 * color palette, fonts, and basic layout of the source presentation.
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { resolve } from 'path'
import { PATHS } from '../utils/config.mjs'
import {
  ensureContrast,
  generateVariants,
  isLightBackground,
  readableOn,
  mix,
} from './palette.mjs'

/**
 * Build a Google Fonts import URL for the given font families.
 * Returns empty string if no fonts provided.
 */
function googleFontsImport(heading, body) {
  const families = []
  if (heading) families.push(`${encodeURIComponent(heading)}:wght@400;700`)
  if (body && body !== heading) families.push(`${encodeURIComponent(body)}:wght@300;400;600`)
  if (!families.length) return ''
  return `@import url('https://fonts.googleapis.com/css2?family=${families.join('&family=')}&display=swap');\n`
}

/**
 * Generate a Marp CSS theme from extracted presentation data.
 *
 * @param {import('../ingest/style-extractor.mjs').ExtractedPresentation} data
 * @param {string} themeName - Name for the generated theme (used in /* @theme ... *\/)
 * @returns {string} Path to the written CSS file
 */
export function generateTheme(data, themeName) {
  const { colorScheme, fonts, dimensions } = data

  const bg = colorScheme.background || '#ffffff'
  const isLight = isLightBackground(bg)

  const primary = colorScheme.primary || (isLight ? '#1a1a1a' : '#ffffff')
  const accent = colorScheme.accent || '#2563eb'
  const textColor = ensureContrast(colorScheme.text || primary, bg)
  const mutedColor = mix(textColor, bg, 40)
  const surfaceColor = isLight ? mix(bg, '#000000', 8) : mix(bg, '#ffffff', 12)
  const borderColor = isLight ? mix(bg, '#000000', 15) : mix(bg, '#ffffff', 20)

  // Invert colors (dark → light or light → dark)
  const invertBg = isLight ? mix(primary, '#000000', 20) : mix(primary, '#ffffff', 20)
  const invertText = readableOn(invertBg)
  const accentVariants = generateVariants(accent)

  // Slide dimensions — normalize to 1280x720 or 960x720
  const w = 1280
  const h = 720

  // Font stacks
  const headingFont = fonts?.heading
    ? `'${fonts.heading}', Georgia, serif`
    : 'Georgia, serif'
  const bodyFont = fonts?.body
    ? `'${fonts.body}', system-ui, sans-serif`
    : 'system-ui, sans-serif'

  const fontsImport = googleFontsImport(fonts?.heading, fonts?.body)

  const css = `/* @theme ${themeName} */
/* Generated by marp-agent-project — do not edit the @theme line */

${fontsImport}
:root {
  --color-primary: ${primary};
  --color-accent: ${accent};
  --color-accent-light: ${accentVariants.light};
  --color-bg: ${bg};
  --color-surface: ${surfaceColor};
  --color-text: ${textColor};
  --color-muted: ${mutedColor};
  --color-border: ${borderColor};
}

section {
  width: ${w}px;
  height: ${h}px;
  padding: 48px 72px;
  background-color: var(--color-bg);
  color: var(--color-text);
  font-family: ${bodyFont};
  font-size: 26px;
  line-height: 1.65;
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  border-top: 5px solid var(--color-accent);
}

h1 {
  font-family: ${headingFont};
  font-size: 50px;
  font-weight: 700;
  color: var(--color-primary);
  margin: 0 0 16px;
  line-height: 1.2;
}

h2 {
  font-family: ${headingFont};
  font-size: 36px;
  font-weight: 700;
  color: var(--color-primary);
  margin: 0 0 24px;
  padding-bottom: 12px;
  border-bottom: 2px solid var(--color-accent);
  line-height: 1.3;
}

h3 {
  font-size: 24px;
  font-weight: 600;
  color: var(--color-accent);
  margin: 0 0 16px;
}

h4, h5, h6 {
  font-size: 20px;
  font-weight: 600;
  color: var(--color-muted);
  margin: 0 0 12px;
}

p { margin: 0 0 16px; }

ul, ol {
  margin: 0 0 16px;
  padding-left: 32px;
}

li { margin-bottom: 10px; }

li::marker { color: var(--color-accent); }

code {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: 4px;
  padding: 2px 8px;
  font-size: 0.83em;
  font-family: 'Courier New', monospace;
}

pre {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-left: 4px solid var(--color-accent);
  border-radius: 4px;
  padding: 20px 24px;
  overflow: auto;
}

pre code {
  background: none;
  border: none;
  padding: 0;
  font-size: 0.74em;
}

table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.84em;
}

th {
  background: var(--color-primary);
  color: ${readableOn(primary)};
  padding: 10px 16px;
  text-align: left;
  font-weight: 600;
}

td {
  padding: 10px 16px;
  border-bottom: 1px solid var(--color-border);
}

blockquote {
  border-left: 4px solid var(--color-accent);
  margin: 0 0 16px;
  padding: 8px 24px;
  color: var(--color-muted);
  font-style: italic;
}

/* Pagination */
section::after {
  content: attr(data-marpit-pagination) ' / ' attr(data-marpit-pagination-total);
  position: absolute;
  bottom: 24px;
  right: 72px;
  font-size: 16px;
  color: var(--color-muted);
}

/* Header / Footer */
header {
  position: absolute;
  top: 16px;
  left: 72px;
  right: 72px;
  font-size: 14px;
  color: var(--color-muted);
  font-weight: 600;
  letter-spacing: 0.05em;
  text-transform: uppercase;
}

footer {
  position: absolute;
  bottom: 24px;
  left: 72px;
  font-size: 14px;
  color: var(--color-muted);
}

/* Lead — title and section slides */
section.lead {
  justify-content: center;
  text-align: center;
  background: var(--color-primary);
  color: ${readableOn(primary)};
  border-top-color: var(--color-accent);
}

section.lead h1 {
  font-size: 58px;
  color: ${readableOn(primary)};
  margin-bottom: 20px;
}

section.lead h2 {
  font-size: 30px;
  color: var(--color-accent-light);
  font-weight: 400;
  border-bottom: none;
  padding-bottom: 0;
}

section.lead p {
  color: ${mix(readableOn(primary), primary, 30)};
}

section.lead::after {
  color: ${mix(readableOn(primary), primary, 50)};
}

/* Invert — dark accent slides */
section.invert {
  background: ${invertBg};
  color: ${invertText};
  border-top-color: var(--color-accent);
}

section.invert h1,
section.invert h2,
section.invert h3 {
  color: ${invertText};
}

section.invert h2 {
  border-bottom-color: var(--color-accent);
}

section.invert li::marker {
  color: var(--color-accent-light);
}

section.invert code {
  background: rgba(0,0,0,0.25);
  border-color: rgba(255,255,255,0.1);
  color: ${invertText};
}

section.invert::after {
  color: ${mix(invertText, invertBg, 40)};
}
`

  const outDir = PATHS.themes
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true })
  const outPath = resolve(outDir, `${themeName}.css`)
  writeFileSync(outPath, css, 'utf8')
  return outPath
}
