/**
 * Marp CSS theme generator.
 *
 * Takes a normalized ExtractedPresentation and produces a valid Marp CSS
 * theme file in the themes/ directory. The generated theme mirrors the
 * color palette, fonts, and basic layout of the source presentation.
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { resolve } from 'path'
import { PATHS } from '../utils/config.mjs'
import {
  ensureContrast,
  generateVariants,
  isLightBackground,
  readableOn,
  mix,
} from './palette.mjs'

function normalizeFontFamily(fontFamily) {
  if (typeof fontFamily !== 'string') return ''
  return fontFamily
    .replace(/[\u0000-\u001f\u007f]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

function escapeCssString(value) {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

function encodeGoogleFontFamily(value) {
  return encodeURIComponent(value).replace(/'/g, '%27')
}

/**
 * Normalize extracted dimensions to supported Marp output sizes.
 * - 16:9-ish sources -> 1280x720
 * - 4:3-ish sources  -> 960x720
 * - Anything else    -> 1280x720
 */
function normalizeThemeDimensions(dimensions) {
  const width = Number(dimensions?.width)
  const height = Number(dimensions?.height)
  if (!Number.isFinite(width) || !Number.isFinite(height) || width <= 0 || height <= 0) {
    return { width: 1280, height: 720 }
  }

  const ratio = width / height
  const widescreenDiff = Math.abs(ratio - 16 / 9)
  const standardDiff = Math.abs(ratio - 4 / 3)

  if (standardDiff < widescreenDiff) {
    return { width: 960, height: 720 }
  }

  return { width: 1280, height: 720 }
}

/**
 * Build a Google Fonts import URL for the given font families.
 * Returns empty string if no fonts provided.
 */
function googleFontsImport(heading, body) {
  const families = []
  if (heading) families.push(`${encodeGoogleFontFamily(heading)}:wght@400;700`)
  if (body && body !== heading) families.push(`${encodeGoogleFontFamily(body)}:wght@300;400;600`)
  if (!families.length) return ''
  return `@import url("https://fonts.googleapis.com/css2?family=${families.join('&family=')}&display=swap");\n`
}

/**
 * Generate a Marp CSS theme from extracted presentation data.
 *
 * @param {import('../ingest/style-extractor.mjs').ExtractedPresentation} data
 * @param {string} themeName - Name for the generated theme (used in /* @theme ... *\/)
 * @returns {string} Path to the written CSS file
 */
export function generateTheme(data, themeName) {
  const { colorScheme, fonts, dimensions } = data
  const resolvedThemeName = String(themeName)

  const bg = colorScheme.background || '#ffffff'
  const isLight = isLightBackground(bg)

  const primary = colorScheme.primary || (isLight ? '#1a1a1a' : '#ffffff')
  const accent = colorScheme.accent || '#2563eb'
  const textColor = ensureContrast(colorScheme.text || primary, bg)
  const mutedColor = mix(textColor, bg, 40)
  const surfaceColor = isLight ? mix(bg, '#000000', 8) : mix(bg, '#ffffff', 12)
  const borderColor = isLight ? mix(bg, '#000000', 15) : mix(bg, '#ffffff', 20)

  // Invert colors (dark → light or light → dark)
  const invertBg = isLight ? mix(primary, '#000000', 20) : mix(primary, '#ffffff', 20)
  const invertText = readableOn(invertBg)
  const accentVariants = generateVariants(accent)

  // Slide dimensions follow normalized source aspect ratio rules.
  const { width: w, height: h } = normalizeThemeDimensions(dimensions)

  const headingFamily = normalizeFontFamily(fonts?.heading)
  const bodyFamily = normalizeFontFamily(fonts?.body)

  // Font stacks
  const headingFont = headingFamily
    ? `'${escapeCssString(headingFamily)}', Georgia, serif`
    : 'Georgia, serif'
  const bodyFont = bodyFamily
    ? `'${escapeCssString(bodyFamily)}', system-ui, sans-serif`
    : 'system-ui, sans-serif'

  const fontsImport = googleFontsImport(headingFamily, bodyFamily)

  const css = `/* @theme ${resolvedThemeName} */
/* Generated by marp-agent-project — do not edit the @theme line */

@import "marpx";
${fontsImport}:root {
  --marpx-theme-font-family: ${bodyFont};
  --marpx-theme-font-size: 26px;
  --marpx-theme-font-color: ${textColor};
  --marpx-theme-background-color: ${bg};
  --marpx-theme-color: ${accent};
  --marpx-theme-h1-color: ${primary};
  --marpx-theme-h1-bold-color: ${accent};
  --marpx-theme-h2-color: ${primary};
  --marpx-theme-bold-color: ${primary};
  --marpx-theme-marker-color: ${accent};
  --marpx-theme-code-color: ${accent};
  --marpx-theme-subtitle-color: ${mutedColor};

  --marpx-theme-accent-light: ${accentVariants.light};
  --marpx-theme-surface-color: ${surfaceColor};
  --marpx-theme-border-color: ${borderColor};
}

section {
  width: ${w}px;
  height: ${h}px;
  padding: 48px 72px;
  background-color: var(--marpx-theme-background-color);
  color: var(--marpx-theme-font-color);
  font-family: var(--marpx-theme-font-family);
  font-size: var(--marpx-theme-font-size);
  line-height: 1.65;
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  border-top: 5px solid var(--marpx-theme-color);
}

h1 {
  font-family: ${headingFont};
  font-size: 50px;
  font-weight: 700;
  color: var(--marpx-theme-h1-color);
  margin: 0 0 16px;
  line-height: 1.2;
}

h2 {
  font-family: ${headingFont};
  font-size: 36px;
  font-weight: 700;
  color: var(--marpx-theme-h2-color);
  margin: 0 0 24px;
  padding-bottom: 12px;
  border-bottom: 2px solid var(--marpx-theme-color);
  line-height: 1.3;
}

h3 {
  font-size: 24px;
  font-weight: 600;
  color: var(--marpx-theme-color);
  margin: 0 0 16px;
}

h4, h5, h6 {
  font-size: 20px;
  font-weight: 600;
  color: var(--marpx-theme-subtitle-color);
  margin: 0 0 12px;
}

p { margin: 0 0 16px; }

ul, ol {
  margin: 0 0 16px;
  padding-left: 32px;
}

li { margin-bottom: 10px; }

li::marker { color: var(--marpx-theme-marker-color); }

code {
  background: var(--marpx-theme-surface-color);
  border: 1px solid var(--marpx-theme-border-color);
  border-radius: 4px;
  padding: 2px 8px;
  font-size: 0.83em;
  font-family: 'Courier New', monospace;
  color: var(--marpx-theme-code-color);
}

pre {
  background: var(--marpx-theme-surface-color);
  border: 1px solid var(--marpx-theme-border-color);
  border-left: 4px solid var(--marpx-theme-marker-color);
  border-radius: 4px;
  padding: 20px 24px;
  overflow: auto;
}

pre code {
  background: none;
  border: none;
  padding: 0;
  font-size: 0.74em;
}

table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.84em;
}

th {
  background: var(--marpx-theme-h1-color);
  color: ${readableOn(primary)};
  padding: 10px 16px;
  text-align: left;
  font-weight: 600;
}

td {
  padding: 10px 16px;
  border-bottom: 1px solid var(--marpx-theme-border-color);
}

blockquote {
  border-left: 4px solid var(--marpx-theme-marker-color);
  margin: 0 0 16px;
  padding: 8px 24px;
  color: var(--marpx-theme-subtitle-color);
  font-style: italic;
}

/* Pagination */
section::after {
  content: attr(data-marpit-pagination) ' / ' attr(data-marpit-pagination-total);
  position: absolute;
  bottom: 24px;
  right: 72px;
  font-size: 16px;
  color: var(--marpx-theme-subtitle-color);
}

/* Header / Footer */
header {
  position: absolute;
  top: 16px;
  left: 72px;
  right: 72px;
  font-size: 14px;
  color: var(--marpx-theme-subtitle-color);
  font-weight: 600;
  letter-spacing: 0.05em;
  text-transform: uppercase;
}

footer {
  position: absolute;
  bottom: 24px;
  left: 72px;
  font-size: 14px;
  color: var(--marpx-theme-subtitle-color);
}

/* Lead — title and section slides */
section.lead {
  justify-content: center;
  text-align: center;
  --marpx-theme-background-color: ${primary};
  --marpx-theme-font-color: ${readableOn(primary)};
  --marpx-theme-h1-color: ${readableOn(primary)};
  --marpx-theme-h2-color: ${accentVariants.light};
  background: var(--marpx-theme-background-color);
  color: ${readableOn(primary)};
  border-top-color: var(--marpx-theme-color);
}

section.lead h1 {
  font-size: 58px;
  color: ${readableOn(primary)};
  margin-bottom: 20px;
}

section.lead h2 {
  font-size: 30px;
  color: var(--marpx-theme-h2-color);
  font-weight: 400;
  border-bottom: none;
  padding-bottom: 0;
}

section.lead p {
  color: ${mix(readableOn(primary), primary, 30)};
}

section.lead::after {
  color: ${mix(readableOn(primary), primary, 50)};
}

/* Invert — dark accent slides */
section.invert {
  --marpx-theme-background-color: ${invertBg};
  --marpx-theme-font-color: ${invertText};
  --marpx-theme-h1-color: ${invertText};
  --marpx-theme-h2-color: ${invertText};
  --marpx-theme-marker-color: ${accentVariants.light};
  background: var(--marpx-theme-background-color);
  color: var(--marpx-theme-font-color);
  border-top-color: var(--marpx-theme-color);
}

section.invert h1,
section.invert h2,
section.invert h3 {
  color: ${invertText};
}

section.invert h2 {
  border-bottom-color: var(--marpx-theme-color);
}

section.invert li::marker {
  color: var(--marpx-theme-marker-color);
}

section.invert code {
  background: rgba(0,0,0,0.25);
  border-color: rgba(255,255,255,0.1);
  color: ${invertText};
}

section.invert::after {
  color: ${mix(invertText, invertBg, 40)};
}
`

  const outDir = PATHS.themes
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true })
  const outPath = resolve(outDir, `${resolvedThemeName}.css`)
  writeFileSync(outPath, css, 'utf8')
  return outPath
}
